language: python

services:
  - docker

install:
  - make deps

script:
  - make lint
  - make test_cov
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  app: pure-mountain-33130
  api_key: ${HEROKU_API_KEY}
